# SPDX-License-Identifier: BSD-3-Clause
# Copyright (C) 2020 Intel Corporation
file (READ VERSION VER_FILE)
string (STRIP "${VER_FILE}" VER_FILE)
string (REPLACE "." ";" VER_LIST ${VER_FILE})
list (GET VER_LIST 0 MEI_VERSION_MAJOR)
list(GET VER_LIST 1 MEI_VERSION_MINOR)
list(GET VER_LIST 2 MEI_VERSION_PATCH)
set(MEI_VERSION_STRING ${MEI_VERSION_MAJOR}.${MEI_VERSION_MINOR}.${MEI_VERSION_PATCH})

